#!/bin/bash

make -s

echo "menuentry "myos" {
	multiboot /boot/myos.bin
}" > grub.cfg

mkdir -p isodir/boot/grub
cp myos.bin isodir/boot/myos.bin
cp grub.cfg isodir/boot/grub/grub.cfg
grub-mkrescue -o myos.iso isodir

# The following line writes to the USB.
sudo dd if=myos.iso of=/dev/sdb && sync
