#!/bin/bash

IMAGE="myos.iso"
VM_MEMORY=500

if [[ -e "$IMAGE" ]]
then
	printf "Starting virtual machine...\n"
	qemu-system-x86_64 -cdrom myos.iso -m $VM_MEMORY 
else
	printf "IMAGE: $IMAGE not found.\n"
fi
